version: '3.2'

services:
  owncloud:
    image: owncloud:fpm # only fpm can connect to Nginx, default port is 9000
    container_name: owncloud_web
    restart: always
    volumes:
      # create the folder ownclouddata before running
      - ownclouddata:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mariadb
    container_name: mariadb_web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      # - ./mysql/config/my.cnf:/etc/my.cnf
      - mariadbdata:/var/lib/mysql # backup file in the host volume
      # - ./mariadb/init:/docker-entrypoint-initdb.d
  
  nginx:
    image: nginx
    container_name: nginx_web
    restart: always
    ports:
      - 5000:80
    volumes:
      - ownclouddata:/var/www/html
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - owncloud

volumes:
  mariadbdata:
  ownclouddata:
