version: '3.2'

services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab_web
    # restart: always
    ports:
    - 80:80
    - 443:443
    - 22:22
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'postgres'
        gitlab_rails['db_password'] = '123'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
    # volumes:
    #   - ./gitlab/config:/etc/gitlab
    #   - ./gitlab/logs:/var/log/gitlab
    #   - ./gitlab/data:/var/opt/gitlab
    depends_on:
      - postgres
      - redis

  postgres:
    # restart: always
    image: postgres:latest
    container_name: postgres_web
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  
  redis:
    # restart: always
    image: redis:latest
    container_name: redis_web
  
  nginx:
    image: nginx
    container_name: nginx_web
    # restart: always
    ports:
      - 5000:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gitlab

volumes:
  postgresdata:
