version: '3.2'

services:
  odoo:
    image: odoo
    container_name: odoo_web
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./oddo/config:/etc/odoo
      - ./oddo/addons:/mnt/extra-addons
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=123
    depends_on:
      - postgres

  postgres:
    # restart: always
    image: postgres:latest
    container_name: postgres_web
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=123
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
  
  # camptocamp/odoo-nginx
  nginx:
    image: nginx
    container_name: nginx_web
    # restart: always
    ports:
      - 5000:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - odoo

volumes:
  postgresdata:
  odoo-web-data:
