version: '3.2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    container_name: rocketchat_web
    environment:
      MONGO_URL: mongodb://mongo:27017/rocketchat
      ROOT_URL: http://localhost:3000/rocketchat
      MAIL_URL: smtp://smtp.email
    ports:
      - 5001:3000
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mongo_web
    image: "mongo"
    # ports:
    #   - 27017:27017
    volumes:
      - mongodbdata:/data/db
  
  nginx:
    image: nginx
    container_name: nginx_web
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rocketchat

volumes:
  mongodbdata:
